<a href="https://colab.research.google.com/github/Nithin611/sample1/blob/main/ML_3_ASS_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PANDAS EX**

In [1]:
#Task 1,2,3
import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')
%cd /content/drive/My Drive/
food = pd.read_csv("en.openfoodfacts.org.products.tsv",sep='\t')

Mounted at /content/drive/
/content/drive/My Drive

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
#Task 4
food.head(5)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Task 5
food.shape[0]

356027

In [4]:
#Task 6
food.shape[1]

163

In [5]:
#Task 7
col=food.columns
col

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

In [6]:
#Task 8
col=food.columns[105]
print(col)

-fructose_100g

In [7]:
#Task 9
print(type(col))

<class 'str'>

In [8]:
#Task 10
print(food.index)

RangeIndex(start=0, stop=356027, step=1)

In [9]:
#Task 11
a=food['product_name']
a[18]

'Lotus Organic Brown Jasmine Rice'

In [10]:
#Task 12
s = food.isnull().any()
print(s.sum())

161

In [11]:
#Task 13
import numpy as np
s=np.array(food.isnull().sum())
print(s)

[    26     26      3      3     10      0      0  17512 298313 236742
 266068 266068  29050  29070 252728 252752 252726 330977 331015 314019
 314026 296929 296849 296823 323537 323541 335155 356001 333525 289462
 298326    275    275    275  72134 318851 356007 327606 327633 327607
 139406 356027  72160  72202 185838 185838  72160 356027 349455  72160
 356027 341699 356027 101171 227021 223338     52     52     52 252778
 252778 280302 280302  60660 355158  76530  92204 356027 356027 356026
 356025 356023 356026 356026 356026 356000 356001 356027 356027 356026
 356027 332987 332952 355089 355826 355984 355938 355820 355868 356018
 356000 356001 356002 356012 356027 356011 356027 356027 356027 212584
 211857  76807  76841 355942 355995 355983 355749 356021 356016 355736
 355576 135344  61866 355998 356010 356018  66288  66333 351450 218321
 355992 348820 354555 355097 214967 344750 345102 344196 349130 350697
 352981 350637 355696 353476 355954 355928 331179 355829 214510 350089
 215367 349635 352063 353905 354388 355928 354846 356004 356007 355739
 355936 355994 355975 352799 355623 355845 354644 356027 355749 101171
 101171 356027 356027]

In [12]:
#Task 14
c=food.columns
sc=[food.shape[0]]*food.shape[1]
d = dict(zip(c,sc))
for i in d:
  print('Column Name :',i,'------Number of rows :',d[i])

Column Name : code ------Number of rows : 356027
Column Name : url ------Number of rows : 356027
Column Name : creator ------Number of rows : 356027
Column Name : created_t ------Number of rows : 356027
Column Name : created_datetime ------Number of rows : 356027
Column Name : last_modified_t ------Number of rows : 356027
Column Name : last_modified_datetime ------Number of rows : 356027
Column Name : product_name ------Number of rows : 356027
Column Name : generic_name ------Number of rows : 356027
Column Name : quantity ------Number of rows : 356027
Column Name : packaging ------Number of rows : 356027
Column Name : packaging_tags ------Number of rows : 356027
Column Name : brands ------Number of rows : 356027
Column Name : brands_tags ------Number of rows : 356027
Column Name : categories ------Number of rows : 356027
Column Name : categories_tags ------Number of rows : 356027
Column Name : categories_en ------Number of rows : 356027
Column Name : origins ------Number of rows : 356027
Column Name : origins_tags ------Number of rows : 356027
Column Name : manufacturing_places ------Number of rows : 356027
Column Name : manufacturing_places_tags ------Number of rows : 356027
Column Name : labels ------Number of rows : 356027
Column Name : labels_tags ------Number of rows : 356027
Column Name : labels_en ------Number of rows : 356027
Column Name : emb_codes ------Number of rows : 356027
Column Name : emb_codes_tags ------Number of rows : 356027
Column Name : first_packaging_code_geo ------Number of rows : 356027
Column Name : cities ------Number of rows : 356027
Column Name : cities_tags ------Number of rows : 356027
Column Name : purchase_places ------Number of rows : 356027
Column Name : stores ------Number of rows : 356027
Column Name : countries ------Number of rows : 356027
Column Name : countries_tags ------Number of rows : 356027
Column Name : countries_en ------Number of rows : 356027
Column Name : ingredients_text ------Number of rows : 356027
Column Name : allergens ------Number of rows : 356027
Column Name : allergens_en ------Number of rows : 356027
Column Name : traces ------Number of rows : 356027
Column Name : traces_tags ------Number of rows : 356027
Column Name : traces_en ------Number of rows : 356027
Column Name : serving_size ------Number of rows : 356027
Column Name : no_nutriments ------Number of rows : 356027
Column Name : additives_n ------Number of rows : 356027
Column Name : additives ------Number of rows : 356027
Column Name : additives_tags ------Number of rows : 356027
Column Name : additives_en ------Number of rows : 356027
Column Name : ingredients_from_palm_oil_n ------Number of rows : 356027
Column Name : ingredients_from_palm_oil ------Number of rows : 356027
Column Name : ingredients_from_palm_oil_tags ------Number of rows : 356027
Column Name : ingredients_that_may_be_from_palm_oil_n ------Number of rows : 356027
Column Name : ingredients_that_may_be_from_palm_oil ------Number of rows : 356027
Column Name : ingredients_that_may_be_from_palm_oil_tags ------Number of rows : 356027
Column Name : nutrition_grade_uk ------Number of rows : 356027
Column Name : nutrition_grade_fr ------Number of rows : 356027
Column Name : pnns_groups_1 ------Number of rows : 356027
Column Name : pnns_groups_2 ------Number of rows : 356027
Column Name : states ------Number of rows : 356027
Column Name : states_tags ------Number of rows : 356027
Column Name : states_en ------Number of rows : 356027
Column Name : main_category ------Number of rows : 356027
Column Name : main_category_en ------Number of rows : 356027
Column Name : image_url ------Number of rows : 356027
Column Name : image_small_url ------Number of rows : 356027
Column Name : energy_100g ------Number of rows : 356027
Column Name : energy-from-fat_100g ------Number of rows : 356027
Column Name : fat_100g ------Number of rows : 356027
Column Name : saturated-fat_100g ------Number of rows : 356027
Column Name : -butyric-acid_100g ------Number of rows : 356027
Column Name : -caproic-acid_100g ------Number of rows : 356027
Column Name : -caprylic-acid_100g ------Number of rows : 356027
Column Name : -capric-acid_100g ------Number of rows : 356027
Column Name : -lauric-acid_100g ------Number of rows : 356027
Column Name : -myristic-acid_100g ------Number of rows : 356027
Column Name : -palmitic-acid_100g ------Number of rows : 356027
Column Name : -stearic-acid_100g ------Number of rows : 356027
Column Name : -arachidic-acid_100g ------Number of rows : 356027
Column Name : -behenic-acid_100g ------Number of rows : 356027
Column Name : -lignoceric-acid_100g ------Number of rows : 356027
Column Name : -cerotic-acid_100g ------Number of rows : 356027
Column Name : -montanic-acid_100g ------Number of rows : 356027
Column Name : -melissic-acid_100g ------Number of rows : 356027
Column Name : monounsaturated-fat_100g ------Number of rows : 356027
Column Name : polyunsaturated-fat_100g ------Number of rows : 356027
Column Name : omega-3-fat_100g ------Number of rows : 356027
Column Name : -alpha-linolenic-acid_100g ------Number of rows : 356027
Column Name : -eicosapentaenoic-acid_100g ------Number of rows : 356027
Column Name : -docosahexaenoic-acid_100g ------Number of rows : 356027
Column Name : omega-6-fat_100g ------Number of rows : 356027
Column Name : -linoleic-acid_100g ------Number of rows : 356027
Column Name : -arachidonic-acid_100g ------Number of rows : 356027
Column Name : -gamma-linolenic-acid_100g ------Number of rows : 356027
Column Name : -dihomo-gamma-linolenic-acid_100g ------Number of rows : 356027
Column Name : omega-9-fat_100g ------Number of rows : 356027
Column Name : -oleic-acid_100g ------Number of rows : 356027
Column Name : -elaidic-acid_100g ------Number of rows : 356027
Column Name : -gondoic-acid_100g ------Number of rows : 356027
Column Name : -mead-acid_100g ------Number of rows : 356027
Column Name : -erucic-acid_100g ------Number of rows : 356027
Column Name : -nervonic-acid_100g ------Number of rows : 356027
Column Name : trans-fat_100g ------Number of rows : 356027
Column Name : cholesterol_100g ------Number of rows : 356027
Column Name : carbohydrates_100g ------Number of rows : 356027
Column Name : sugars_100g ------Number of rows : 356027
Column Name : -sucrose_100g ------Number of rows : 356027
Column Name : -glucose_100g ------Number of rows : 356027
Column Name : -fructose_100g ------Number of rows : 356027
Column Name : -lactose_100g ------Number of rows : 356027
Column Name : -maltose_100g ------Number of rows : 356027
Column Name : -maltodextrins_100g ------Number of rows : 356027
Column Name : starch_100g ------Number of rows : 356027
Column Name : polyols_100g ------Number of rows : 356027
Column Name : fiber_100g ------Number of rows : 356027
Column Name : proteins_100g ------Number of rows : 356027
Column Name : casein_100g ------Number of rows : 356027
Column Name : serum-proteins_100g ------Number of rows : 356027
Column Name : nucleotides_100g ------Number of rows : 356027
Column Name : salt_100g ------Number of rows : 356027
Column Name : sodium_100g ------Number of rows : 356027
Column Name : alcohol_100g ------Number of rows : 356027
Column Name : vitamin-a_100g ------Number of rows : 356027
Column Name : beta-carotene_100g ------Number of rows : 356027
Column Name : vitamin-d_100g ------Number of rows : 356027
Column Name : vitamin-e_100g ------Number of rows : 356027
Column Name : vitamin-k_100g ------Number of rows : 356027
Column Name : vitamin-c_100g ------Number of rows : 356027
Column Name : vitamin-b1_100g ------Number of rows : 356027
Column Name : vitamin-b2_100g ------Number of rows : 356027
Column Name : vitamin-pp_100g ------Number of rows : 356027
Column Name : vitamin-b6_100g ------Number of rows : 356027
Column Name : vitamin-b9_100g ------Number of rows : 356027
Column Name : folates_100g ------Number of rows : 356027
Column Name : vitamin-b12_100g ------Number of rows : 356027
Column Name : biotin_100g ------Number of rows : 356027
Column Name : pantothenic-acid_100g ------Number of rows : 356027
Column Name : silica_100g ------Number of rows : 356027
Column Name : bicarbonate_100g ------Number of rows : 356027
Column Name : potassium_100g ------Number of rows : 356027
Column Name : chloride_100g ------Number of rows : 356027
Column Name : calcium_100g ------Number of rows : 356027
Column Name : phosphorus_100g ------Number of rows : 356027
Column Name : iron_100g ------Number of rows : 356027
Column Name : magnesium_100g ------Number of rows : 356027
Column Name : zinc_100g ------Number of rows : 356027
Column Name : copper_100g ------Number of rows : 356027
Column Name : manganese_100g ------Number of rows : 356027
Column Name : fluoride_100g ------Number of rows : 356027
Column Name : selenium_100g ------Number of rows : 356027
Column Name : chromium_100g ------Number of rows : 356027
Column Name : molybdenum_100g ------Number of rows : 356027
Column Name : iodine_100g ------Number of rows : 356027
Column Name : caffeine_100g ------Number of rows : 356027
Column Name : taurine_100g ------Number of rows : 356027
Column Name : ph_100g ------Number of rows : 356027
Column Name : fruits-vegetables-nuts_100g ------Number of rows : 356027
Column Name : fruits-vegetables-nuts-estimate_100g ------Number of rows : 356027
Column Name : collagen-meat-protein-ratio_100g ------Number of rows : 356027
Column Name : cocoa_100g ------Number of rows : 356027
Column Name : chlorophyl_100g ------Number of rows : 356027
Column Name : carbon-footprint_100g ------Number of rows : 356027
Column Name : nutrition-score-fr_100g ------Number of rows : 356027
Column Name : nutrition-score-uk_100g ------Number of rows : 356027
Column Name : glycemic-index_100g ------Number of rows : 356027
Column Name : water-hardness_100g ------Number of rows : 356027

In [13]:
#Task 15
food[108:209]

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
108,36252,http://world-en.openfoodfacts.org/product/0000...,tacinte,1422221701,2015-01-25T21:35:01Z,1494824741,2017-05-15T05:05:41Z,Lion Peanut x2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,36269,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055651,2017-03-09T10:34:11Z,1489055651,2017-03-09T10:34:11Z,Milk Chocolate Peanut Butter Malt Balls,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23.0,23.0,NaN,NaN
110,36276,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055678,2017-03-09T10:34:38Z,1489055678,2017-03-09T10:34:38Z,Organic Tamari Pumpkin Seed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,NaN,NaN
111,36986,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055649,2017-03-09T10:34:09Z,1489055649,2017-03-09T10:34:09Z,Yogurt Pretzels,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,30.0,30.0,NaN,NaN
112,38058,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055651,2017-03-09T10:34:11Z,1489055651,2017-03-09T10:34:11Z,Organic Kamut Flakes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,20043087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489135780,2017-03-10T08:49:40Z,1489135780,2017-03-10T08:49:40Z,Biscuit,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18.0,18.0,NaN,NaN
205,20043124,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489133902,2017-03-10T08:18:22Z,1489133902,2017-03-10T08:18:22Z,Oatmeal Raisin Cookie,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,21.0,21.0,NaN,NaN
206,20043131,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489133434,2017-03-10T08:10:34Z,1489133434,2017-03-10T08:10:34Z,Sliced Plain Bagel,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN
207,20044015,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489133902,2017-03-10T08:18:22Z,1489133902,2017-03-10T08:18:22Z,Scone,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.0,19.0,NaN,NaN
208,20044480,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489133434,2017-03-10T08:10:34Z,1489133434,2017-03-10T08:10:34Z,Belgian Vanilla Waffle,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,25.0,25.0,NaN,NaN